[[actions]]
name = "VirtualXT - FreeDOS"
path = "VirtualXT-x86_64.AppImage"

#[[actions]]
#name = "Boot Floppy Image"
#path = "VirtualXT-x86_64.AppImage"

[[actions]]
name = "manual"
path = "VirtualXT-x86_64.AppImage"
args = ["-m"]