name: Tests

on:
  push:
    branches: [ "develop", "edge", "release" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  linux-build:
    name: Tests (Linux AMD64)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install kcov
          curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz && mkdir premake5 && tar -xf premake5.tar.gz -C premake5
          echo "${GITHUB_WORKSPACE}/premake5" >> $GITHUB_PATH

      - name: Generate
        run: ./tools/tests/8088v1/generate.py

      - name: Premake
        run: premake5 --test gmake

      - name: Test
        run: make clean test

      - name: Report
        run: |
          kcov --include-path=lib/vxt --exclude-path=lib/vxt/include,lib/vxt/test \
          --exclude-pattern=cga.c,disk.c,dma.c,dummy.c,mda.cmemory.c,mouse.c,pic.c,pit.c,ppi.c,uart.c,utils.c,v20.inl \
          kcov-out test/test .

      - name: Upload
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash) -s kcov-out