name: Web

on:
  push:
    branches: [ "develop", "edge", "release" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

env:
  VXT_VERSION: 0.11.0

jobs:
  web-build:
    name: Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Setup
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip -d butler
          curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz && mkdir premake5 && tar -xf premake5.tar.gz -C premake5
          echo "${GITHUB_WORKSPACE}/butler" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/premake5" >> $GITHUB_PATH

      - name: Test
        run: |
          premake5 --test gmake
          make clean test

      - name: Build
        run: |
          premake5 --modules=ctrl,cga --static gmake
          make config=release_web clean web-frontend

      - name: Package
        run: |
          cd build/web
          zip -r ../../virtualxt.zip .
          cd ../..
        
      - name: Deploy
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: if [[ $GITHUB_REF_NAME =~ ^(edge)$ ]]; then ./tools/package/itch/push-web.sh; fi
